package com.example.demo.entity;



public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.firstName
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.lastName
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phoneNumber
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.hireDate
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private String hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.salary
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.commissionPct
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    private Integer commissionpct;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public Employee(String firstname, String lastname, String email, String phonenumber, String hiredate, Integer salary, Integer commissionpct) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.phonenumber = phonenumber;
        this.hiredate = hiredate;
        this.salary = salary;
        this.commissionpct = commissionpct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public Employee() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.firstName
     *
     * @return the value of employee.firstName
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.firstName
     *
     * @param firstname the value for employee.firstName
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.lastName
     *
     * @return the value of employee.lastName
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.lastName
     *
     * @param lastname the value for employee.lastName
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phoneNumber
     *
     * @return the value of employee.phoneNumber
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phoneNumber
     *
     * @param phonenumber the value for employee.phoneNumber
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.hireDate
     *
     * @return the value of employee.hireDate
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public String getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.hireDate
     *
     * @param hiredate the value for employee.hireDate
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setHiredate(String hiredate) {
        this.hiredate = hiredate == null ? null : hiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.salary
     *
     * @return the value of employee.salary
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.salary
     *
     * @param salary the value for employee.salary
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.commissionPct
     *
     * @return the value of employee.commissionPct
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public Integer getCommissionpct() {
        return commissionpct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.commissionPct
     *
     * @param commissionpct the value for employee.commissionPct
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    public void setCommissionpct(Integer commissionpct) {
        this.commissionpct = commissionpct;
    }
}