package com.example.demo.mapper;

import com.example.demo.entity.Employee;
import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    //int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Wed Jul 24 13:41:12 CST 2019
     */
    //int insertSelective(Employee record);

    List<Employee> findAllEmployee();
}